name: Release Built Blender Addon ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we need full history to collect changes correctly
          fetch-depth: 0

      - name: Build project
        run: make build-addon

      - name: Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: __releases__/*.zip
          body: ${{ steps.changes.outputs.changes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
